### ISSUE TITLE
Add new tag

### ISSUE THREAD

**Issue by evtushenko-sasha** [JavaBraveWarriors/blog-client#13]
### List of changes:
* Add the ability to add new tag.
![screenshot from 2019-02-24 19-07-26](https://user-images.githubusercontent.com/32134385/53301722-752a3c80-3867-11e9-8798-fad226c562bb.png)

**Comment by aleksieiev** [comment]
1. Please add some information about behavior of the page when something is being entering in the field "Tag name". From my point of view there are a few possible cases:
- just brand new tag will be added
- AJAX request will be sent to server which returns already exists tags
- something mixed.
2. What if tag already exists?
3. Does tag name case sensitive?
4. Can tag contain special characters? E.g.: $#%^
5. What does it mean "Отправить"? Where tag will be sent after pressing button? It's not clear for me about process of adding new tag. Can I add new tag during article writing process? Or I should create all required tags before creating an article.
6. Feedback message for user: will he receive any information about operation result? Which form has been chosen (popup message, no any message about result at all)?

**Comment by evtushenko-sasha** [comment]
* When the user clicks the add (+) button in the header, a form appears with the addition of a new tag,
when the user entered the data and clicked send, an ajax request to the server occurs,
1) If the tag exists, a message should be displayed stating that the tag already exists
2) Tag name is not case sensitive
3) The name can contain any characters.
4) You can add a tag at any time, if you are at the stage of writing an article, you will have to reload the page so that the tag appears in the list
5) If the request is successful, a modal window is displayed to the user about successful addition
![screenshot from 2019-02-26 13-34-41](https://user-images.githubusercontent.com/32134385/53406595-51800700-39cb-11e9-868e-f3a87357f664.png)

**Comment by aleksieiev** [comment]
Result message isn't informative. After fixing it we're ready to PR #14

**Comment by evtushenko-sasha** [comment]
Implemented in #14 PR.
