### ISSUE TITLE
Update tag.

### ISSUE THREAD

**Issue by evtushenko-sasha** [JavaBraveWarriors/blog-client#15]
### List of changes:
* ![screenshot from 2019-02-26 14-18-28](https://user-images.githubusercontent.com/32134385/53409198-6c557a00-39d1-11e9-8a38-79decd1a2c5a.png)
* When the user clicks to customize the tag, a form will open with the data that this tag already had
![screenshot from 2019-02-26 14-27-03](https://user-images.githubusercontent.com/32134385/53409687-a2dfc480-39d2-11e9-8ddb-374623cef10b.png)
* Tag update nuances are the same as tag adding, see #13 
* If the tag is updated successfully, a message appears:
![screenshot from 2019-02-26 14-32-45](https://user-images.githubusercontent.com/32134385/53409939-69f41f80-39d3-11e9-9fb9-4c50e72d5375.png)

**Comment by aleksieiev** [comment]
Shut up and implement it ASAP!
It's the best issue description for now. I'll save link on it too close to my heart and provide it any time when my team and me will have any misunderstandings about story description details and best practices.
Great job!

**Comment by evtushenko-sasha** [comment]
Implemented in #14 PR.
