### ISSUE TITLE
Delete tag

### ISSUE THREAD

**Issue by evtushenko-sasha** [JavaBraveWarriors/blog-client#16]
### List of changes:
* When the user clicks on the trash icon
![screenshot from 2019-02-26 14-18-28](https://user-images.githubusercontent.com/32134385/53410173-13d3ac00-39d4-11e9-9d4d-63cd5b4e0979.png)
* Confirmation window appears
![screenshot from 2019-02-26 14-46-10](https://user-images.githubusercontent.com/32134385/53410580-4e8a1400-39d5-11e9-863d-e95f20a7e409.png)
* If the user agrees, the request will be sent to server, and  tag will be deleted.
* If user disagrees, modal will be closed, and tag will not deleted

**Comment by aleksieiev** [comment]
Minor question.
What about posts with that tag? Suppose we have a post just with one tag which has been removed.  Where will it placed? As far as I see current implementation there're no block w/o tags.
See screenshot in your comment here #13

**Comment by evtushenko-sasha** [comment]
When there is a transition to posts, they are not selected by tags at the moment, so I did not do the implementation of the transition to posts that do not have a tag.
In the future, most likely this page will not be, something like that will remain only with the administrator to manage tags.
All interaction will take place through a page with posts, where there will be all sorts of filtering.

**Comment by aleksieiev** [comment]
Ok, clear.

**Comment by evtushenko-sasha** [comment]
Implemented in #14 PR.
