### ISSUE TITLE
Page add new post. Estimated time spent 8 hours.

### ISSUE THREAD

**Issue by evtushenko-sasha** [JavaBraveWarriors/blog-client#2]
![screenshot from 2019-02-07 14-49-44](https://user-images.githubusercontent.com/32134385/52409849-bc82a000-2ae7-11e9-926e-06fde8f948b0.png)
In this page users may to add new post.

**Comment by aleksieiev** [comment]
Ugly.
1. Why name of the issue contains estimation time?
2. Add acceptance issue criteria: what will be if post text is empty? which fields are required? How will page looks like after successful adding post?

**Comment by evtushenko-sasha** [comment]
Implemented in [this](https://github.com/JavaBraveWarriors/blog-client/commit/2521026aa03d3bcd9a652ff03624456807784f02) commit.
