### ISSUE TITLE
Result of Spike (Adding ActiveMQ in project.)

### ISSUE THREAD

**Issue by evtushenko-sasha** [JavaBraveWarriors/blog-client#20]
* ActiveMQ will be installed via docker, there are ready builds:
```
$ docker pull rmohr/activemq
$ docker run -p 61616:61616 -p 8161:8161 rmohr/activemq
```
* I will need to make a connection to rest-api through ActiveMQ using the JmsTemplate for adding comments and tags.
* Requests for adding a tag and a comment will work through ActiveMQ queue using JSM, all other requests will go directly to rest-api using HTTP.
* At the moment, the interaction takes place through a direct connection with the rest-api.
* After implementation, the connection must pass through a special ActiveMQ service that contains queues, this will reduce the waiting time, because the restTemplate always waits for a response from rest-api, and the JmsTemplate works asynchronously and has not needed to wait response.
* 2 queues must be created on ActiveMQ, one for tags, one for comments.
* It may also be necessary to create a queue for errors that come with rest-api, because it necessary according to the technical task to send errors back to the client.
Post-implementation interaction simplified scheme:
![screenshot from 2019-03-01 12-46-31](https://user-images.githubusercontent.com/32134385/53629996-1296bf00-3c20-11e9-9088-bbd26d16ef58.png)

**Comment by aleksieiev** [comment]
1. Results of spike should be at the same place where spike has been described.
2. Even if it's required to place spike results in a different place it's **obligatory** to provide the link to the basic spike (not the name, but real link!). Try to guess why at your free time.
3. As we discussed before I didn't see spike goal: what questions should be answered. Answers should be provided based on this. So, for me now it's unstructured yet.

As for task in general. Looks reasonable, so it might be used for development.
