### ISSUE TITLE
Page with tags. Estimated time spent 8 hours.

### ISSUE THREAD

**Issue by evtushenko-sasha** [JavaBraveWarriors/blog-client#3]
![screenshot from 2019-02-06 15-10-32](https://user-images.githubusercontent.com/32134385/52410037-3ca90580-2ae8-11e9-84a7-7adcd0b03e3e.png)

**Comment by aleksieiev** [comment]
The same like [here](https://github.com/JavaBraveWarriors/blog-client/issues/2)

**Comment by evtushenko-sasha** [comment]
Implemented in [this](https://github.com/JavaBraveWarriors/blog-client/commit/6d3bb829ec2e9ba952ca776573ea9e09d17fe0a5) commit.
