### ISSUE TITLE
Page with one post.

### ISSUE THREAD

**Issue by evtushenko-sasha** [JavaBraveWarriors/blog-client#4]
![screenshot from 2019-02-19 14-09-43](https://user-images.githubusercontent.com/32134385/53010890-13756700-3450-11e9-8b75-559d5852c58a.png)

### List of changes:
* Create a page to display one post
* Add the ability to view comments page by page without refreshing the page.
* Add the ability to add / delete / edit comments without updating the page

**Comment by aleksieiev** [comment]
Approved. Waiting for PR

**Comment by evtushenko-sasha** [comment]
Implemented in [this](https://github.com/JavaBraveWarriors/blog-client/tree/66960fd8e101333ad2ba5c89793f975f7c404781
) commit.
